### ISSUE TITLE
Craft Presence Crash 

### ISSUE THREAD

**Issue by FallenEagle1** [CDAGaming/CraftPresence#1]
[crash-2018-08-07_15.49.30-client.txt](https://github.com/CDAGaming/CraftPresence/files/2268248/crash-2018-08-07_15.49.30-client.txt)

Modpack: All the Mods 3. This is a test version of the pack for the 6.0 update 5.9.8d is for the mods part similar.
CraftPresence: 1.2.0.113
Forge: 14.23.4.2739

This is on a Windows10 machine, and it seems to not like something with the .dll files. I don't believe this affects other OS systems like it does for win10.

**Comment by CDAGaming** [comment]
@FallenEagle1 Does this Issue also exist in v1.3.0 also (v1.3 is the Newest Stable Release)?

**Comment by FallenEagle1** [comment]
Just tested with 1.3.0.134 and same crash. Can upload it also if you want, but just looking through the stacktrace for the crash, it looks to be very similar if not the same.

**Comment by FallenEagle1** [comment]
I believe discordSuite was having this issue as well, but wasn't seeing an issue about it to reference. Looking through the commits, maybe the one labelled "Add Files via Upload"

**Comment by CDAGaming** [comment]
I noticed in your first crash that your using MutliMC.

If this is correct, please check your Instances .minecraft Folder for a "craftpresence" folder, and Let me know if you see this folder, and if there is anything in it.

**Comment by FallenEagle1** [comment]
Not seeing one. Just the jar file and the config file.

**Comment by CDAGaming** [comment]
[Debug20180807.zip](https://github.com/CDAGaming/CraftPresence/files/2268348/Debug20180807.zip)
@FallenEagle1 See if you can run the game with this JAR. If it crashes on this one, send me your latest.log 
(I've set up a ton of logging around getting the Libraries, this way I can see what is currently breaking for you)

**Comment by FallenEagle1** [comment]
[latest.log](https://github.com/CDAGaming/CraftPresence/files/2268363/latest.log)

**Comment by FallenEagle1** [comment]
Can grab debug as well. Just for ease of setting it up, just made a custom profile in twitch and put only craftpresence into it.

**Comment by CDAGaming** [comment]
This appears to be an Issue with your User Permissions
(CraftPresence requires the ability to read/write the library file in your .minecraft).

I'll send a new build shortly to double check on what Perms are needed to be able to have the Library Work:

Log Ref: `C:\Users\njhof\Documents\Games\Curse\Instances\Test\craftpresence\win32-x86-64\discord-rpc.dll: Access is denied`

**Comment by FallenEagle1** [comment]
That sounds about right, but I believe that is what most win10 machines are default to. Very least, I haven't changed anything with my user permissions (never had to) and users of the pack will be in the same boat.

**Comment by CDAGaming** [comment]
Neither have I, which makes this case very strange 
(This was only encountered once before, for most the mod was able to load the libraries no problem)
[Debug_20180807_Build2.zip](https://github.com/CDAGaming/CraftPresence/files/2268393/Debug_20180807_Build2.zip)

If this crashes still, please send once again your latest.log 
(Only change on this one, is to give a log checking the read/write perms in the directory)

**Comment by CDAGaming** [comment]
Question: In the Twitch Profile you created earlier, did it contain a "craftpresence" folder (In this case, it should be at "C:\Users\njhof\Documents\Games\Curse\Instances\Test\craftpresence"

**Comment by FallenEagle1** [comment]
yep it did. in it was a folder labelled win32-x86-64 and has a folder in it labelled discord-rpc.dll. There is nothing in that folder.

**Comment by CDAGaming** [comment]
Closed as Fixed (Will be Included in v1.3.5)
