### ISSUE TITLE
Mod Crashes on startup due to failure to load config

### ISSUE THREAD

**Issue by Jonathing** [CDAGaming/CraftPresence#2]
Failure to load or save Configuration, as well as failure to load display data cause the game to crash upon startup. Obviously, the mod is trying to load something that doesn't exist. This might be because of an update that has been imposed by the configuration loading system.

I am on commit 8557b90

https://gist.github.com/Jonathing/67cfd576e63336e64b46ea221059401e

If I find time to work on this issue, I will. However, my life is a mess right now. Lol.

**Comment by Jonathing** [comment]
One of the main reasons I can't help you with this is because I don't fully understand the Discord RPC code you made for the mod.

**Comment by CDAGaming** [comment]
Closing this Issue due to Reasons explained.

Once the GUI is completed, and I'm able to make any needed Cleanups, I'll put in either a migration or removal method for old configs.

**Comment by Jonathing** [comment]
Can you at least send me a gist of your config file so I can look at the config gui itself?

**Comment by CDAGaming** [comment]
Marked as Fixed: https://github.com/CDAGaming/CraftPresence/commit/94c2aa34c609457834686f0d8cb11ec7286f5077
